pipeline {
  agent any
  tools {
    maven 'mvn'
    jdk 'JDK 8'
  }
  stages {
    stage('Remove old and create and start new container') {
      steps{
        sh '''
          $SSH_COMMAND "
          sudo -u docker docker rm -f teamengine-beta
          sudo -u docker docker pull ogccite/teamengine-beta:latest
          sudo -u docker docker run -d --name teamengine-beta -p 8082:8080 -v /srv/local/team.dat/te-beta-users1:/root/te_base/users --restart unless-stopped ogccite/teamengine-beta:latest
          "
          '''
      }
    }
    stage('Apply teamengine-site') {
      steps{
        sh '''
          $SSH_COMMAND "
          mkdir tmp-teamengine-site
          cd tmp-teamengine-site
          git clone https://github.com/opengeospatial/teamengine-site.git
          mv teamengine-site/site-beta/ teamengine-site/site/
          sudo -u docker docker exec teamengine-beta rm -r /root/te_base/resources/site/
          sudo -u docker docker cp teamengine-site/site teamengine-beta:/root/te_base/resources/site/
          sudo -u docker docker restart teamengine-beta
          cd ..
          rm -rf tmp-teamengine-site/
          "
          '''
      }
    }
  }
}
